version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: slot_db_container
    restart: always
    environment:
      POSTGRES_DB: simulator_slot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"

  app:
    build: ..
    container_name: slot_app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simulator_slot
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db