spring.application.name=crystal.slot
spring.datasource.url=jdbc:postgresql://localhost:5432/simulator_slot
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update